workspace:
  base: /build
  path: src/github.com/ukhomeoffice/private-api-server

pipeline:
  test:
      image: node:8
      environment:
        - GRADLE_USER_HOME=~/.gradle
      commands:
        - ./gradlew test
      when:
        event:
        - push
        - pull_request

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      status:
        - failure
        - success
      event:
        - push
        - pull_request

  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_name
    commands:
      - docker build -t $${DOCKER_NAME} .
    when:
      event:
        - push
        - pull_request

  image_to_quay:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_username
      - docker_password
      - docker_server
      - docker_group
      - docker_name
    commands:
    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} $${DOCKER_SERVER}
    - docker tag $${DOCKER_NAME} $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:latest
    - docker push $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:latest
    when:
      branch: master
      event: push

  tag_image_to_quay:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_username
      - docker_password
      - docker_server
      - docker_group
      - docker_name
    commands:
    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} $${DOCKER_SERVER}
    - docker tag $${DOCKER_NAME} $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:$${DRONE_COMMIT_SHA}
    - docker push $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: tag

